# Numpy- Numerical Python

In [2]:
import numpy as np

In [5]:
# numpy Array- Its homogeneous.
a=np.array([3,4,5])
a


array([3, 4, 5])

In [6]:
print(a)

[3 4 5]


In [7]:
print(a)
print('Dimension:',a.ndim) # gives dimension of array
print('Element Type:',a.dtype) #Data type

[3 4 5]
Dimension: 1
Element Type: int32


In [12]:
print('Shape:',a.shape)

Shape: (3,)


In [14]:
#create a 2-d array
a=np.array([[3,4,5],[7,8,6]])
a

array([[3, 4, 5],
       [7, 8, 6]])

In [15]:
print(a)

[[3 4 5]
 [7 8 6]]


In [16]:
print('shape:',a.shape)

shape: (2, 3)


In [22]:
print(a)
print('Dimension:',a.ndim)
print('Size:',a.size)
print('Element Type:', a.dtype)
print('shape:',a.shape)      

[[3 4 5]
 [7 8 6]]
Dimension: 2
Size: 6
Element Type: int32
shape: (2, 3)


In [23]:
# from above read from right side , 3(3,4,5)(7,8,6) elements in 1-d, 
# 2 elements in 2-d(both rows acts as 2-d)

# create an array of(2,3,2)


In [25]:
a=np.array([[2,3],[4,5],[6,7]])
print(a)

[[2 3]
 [4 5]
 [6 7]]


In [27]:
f=np.array([
          [] [1,1],
           [2,2],
           [3,3]],
           
          [[4,4],
           [5,5],
           [6,6]])

TypeError: data type not understood

In [28]:
print(f)
print('Dimension:',f.ndim)
print('Size:',f.size)
print('Element Type:', f.dtype)
print('shape:',f.shape)   

NameError: name 'f' is not defined

# Arange

In [29]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.arange(25).reshape(3,5)

ValueError: cannot reshape array of size 25 into shape (3,5)

In [39]:
np.arange(25).reshape(5,5) # reshape product should be same as the arange number so that it exactly fits.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
np.arange(10,100,5).reshape(3,6) # (start,stop,step) 

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [42]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Linspace

In [55]:
np.linspace(10,100,5,dtype=int) # Linspace (start,stop, no.of elements instead of step)

array([ 10,  32,  55,  77, 100])

# Reshape


In [56]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
# Create 6-d data with arange having 6 elements in 1-d 
f= np.arange(6).reshape(1,1,1,1,1,6)

In [59]:
print(f)
print('Dimension:',f.ndim)
print('Size:',f.size)
print('Element Type:', f.dtype)
print('shape:',f.shape)  

[[[[[[0 1 2 3 4 5]]]]]]
Dimension: 6
Size: 6
Element Type: int32
shape: (1, 1, 1, 1, 1, 6)


# Ravel

In [61]:
f= f.ravel() # changes any dimension to 1-d
f

array([0, 1, 2, 3, 4, 5])

In [63]:
print('Dimension:',f.ndim)

Dimension: 1


In [68]:
a=np.array([[3,4,5],[7,8,6]])
a

array([[3, 4, 5],
       [7, 8, 6]])

In [69]:
a.ravel()

array([3, 4, 5, 7, 8, 6])

# Random Numbers

In [70]:
np.random.rand()

0.8612915930307669

In [71]:
np.random.rand()*100

20.679490250207223

In [73]:
int(np.random.rand()*100) #to remove an integer

4

In [74]:
np.random.rand(5)

array([0.42742409, 0.47396437, 0.28336109, 0.4768929 , 0.71426888])

In [79]:
np.random.randint(35,100) #random int btwn 35 to 100

70

In [80]:
#Create an array with random of 50, reshape it to 50,10 and take square root of it.

In [82]:
np.sqrt(np.random.randint(35,100,50).reshape(5,10))

array([[9.48683298, 8.88819442, 8.54400375, 9.79795897, 9.59166305,
        6.164414  , 9.48683298, 9.64365076, 9.79795897, 6.70820393],
       [6.40312424, 9.89949494, 6.40312424, 8.88819442, 7.81024968,
        8.42614977, 7.68114575, 7.54983444, 8.1240384 , 9.89949494],
       [8.48528137, 9.53939201, 9.43398113, 9.43398113, 6.63324958,
        8.54400375, 8.        , 7.28010989, 6.8556546 , 6.70820393],
       [6.164414  , 6.78232998, 9.89949494, 8.94427191, 6.8556546 ,
        9.53939201, 8.18535277, 9.8488578 , 7.28010989, 5.91607978],
       [9.2736185 , 9.53939201, 6.164414  , 8.77496439, 7.21110255,
        8.42614977, 9.74679434, 7.74596669, 9.74679434, 8.77496439]])

In [83]:
np.sqrt(np.random.rand(100))

array([0.84792619, 0.36581666, 0.96429501, 0.36338462, 0.61115643,
       0.88058413, 0.93160411, 0.83956909, 0.63582657, 0.80702718,
       0.8164583 , 0.582125  , 0.32373748, 0.63256326, 0.88346978,
       0.80368338, 0.64658512, 0.95767799, 0.81642425, 0.5293687 ,
       0.19096975, 0.42649668, 0.93039182, 0.28601315, 0.74057571,
       0.65221309, 0.29892833, 0.76909238, 0.56515871, 0.82544568,
       0.96606525, 0.82208991, 0.49691976, 0.85180232, 0.4073421 ,
       0.76335557, 0.70268273, 0.96072741, 0.69381474, 0.30725835,
       0.92748783, 0.97331036, 0.92502928, 0.80631128, 0.53198131,
       0.93855207, 0.7524447 , 0.55209856, 0.94390806, 0.65152382,
       0.04930364, 0.87754893, 0.64314818, 0.05321333, 0.95646961,
       0.87859822, 0.88299547, 0.52840736, 0.46657339, 0.58357928,
       0.35960641, 0.47823713, 0.95232271, 0.59232328, 0.25693266,
       0.9042666 , 0.89140111, 0.87207571, 0.54545664, 0.72463897,
       0.91204774, 0.89709876, 0.71958999, 0.93105626, 0.85208

In [88]:
np.random.randint(30,100,50).reshape(10,5) # random nos from 30 to 100 and we need 50 nos of those

array([[60, 78, 92, 33, 37],
       [98, 51, 35, 59, 50],
       [87, 59, 98, 99, 84],
       [87, 78, 81, 39, 70],
       [70, 86, 76, 39, 72],
       [85, 61, 98, 32, 95],
       [65, 47, 44, 39, 51],
       [97, 63, 80, 63, 66],
       [74, 71, 52, 65, 40],
       [36, 78, 56, 99, 32]])

In [92]:
np.around(4.6) # rounf off to nearer number

5.0

np.sqrt(np.random.randint(40,100,20).reshape(4,5))

In [90]:
np.floor(4.2) # round off to lower value 

4.0

In [91]:
np.ceil(4.2) # rounf off to higher values

5.0

# Horizontal Split & Vertical Split

In [94]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [96]:
np.vsplit(a,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [98]:
np.hsplit(a,2)[0] # to obtain first part of array

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [100]:
np.hsplit(a,2)[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [102]:
np.vsplit(a,3)[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

# Horizontal Stack and Vertical Stack

In [110]:
a=np.arange(9).reshape(3,3)
b=np.arange(20,29).reshape(3,3)
print(a)
print('\n')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [104]:
np.hstack((a,b))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])

In [106]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

# Add 2 integers to an array amd type cast it to float

In [114]:
a=np.array((2+5,6+3),dtype='float')
print(a)
print(a.dtype)

[7. 9.]
float64
